In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Problem

In [2]:
'''
check whether given [9,9,9,9,9], [0,0,0,0,0], [10,10,10,10,10] are 0 or 1 respectively.
'''

'\ncheck whether given [9,9,9,9,9], [0,0,0,0,0], [10,10,10,10,10] are 0 or 1 respectively.\n'

In [3]:
x_data = [[1,1,1,1,1], [2,2,2,2,2], [3,3,3,3,3], [4,4,4,4,4], [5,5,5,5,5], [6,6,6,6,6], [7,7,7,7,7]]
y_data = [[0], [0], [0], [1], [1], [1], [1]]

# solution

In [4]:
X= tf.placeholder(tf.float32, shape=[None, 5]) #dim of x_data = 5
Y= tf.placeholder(tf.float32, shape=[None, 1])

W= tf.Variable(tf.random_normal([5, 1]), name='weight')
b= tf.Variable(tf.random_normal([1]), name='bias')

model= tf.add(tf.matmul(X, W), b) #linear regression
model= tf.sigmoid(model) # Logistic(sigmoid)

cost= tf.reduce_mean((-1)*Y*tf.log(model)+(-1)*(1-Y)*tf.log(1-model))

train=tf.train.GradientDescentOptimizer(learning_rate=0.15).minimize(cost)

prediction = tf.cast(model>0.5, dtype=tf.float32)
accuracy= tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype=tf.float32))

In [5]:
sess= tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10001):
    cost_val, _=sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print(step, cost_val)

0 1.7290534
200 0.22636566
400 0.16698685
600 0.13857782
800 0.12108304
1000 0.108844474
1200 0.0996074
1400 0.09227841
1600 0.0862553
1800 0.08117544
2000 0.07680518
2200 0.07298628
2400 0.06960694
2600 0.066585295
2800 0.063860156
3000 0.061384458
3200 0.059121132
3400 0.057040814
3600 0.055119544
3800 0.053337723
4000 0.051679123
4200 0.050130066
4400 0.048679028
4600 0.047316123
4800 0.046032853
5000 0.04482188
5200 0.04367673
5400 0.042591758
5600 0.041561995
5800 0.04058316
6000 0.03965125
6200 0.038762715
6400 0.037914492
6600 0.03710378
6800 0.036327947
7000 0.035584647
7200 0.03487187
7400 0.03418767
7600 0.033530287
7800 0.03289803
8000 0.03228962
8200 0.03170352
8400 0.03113852
8600 0.030593531
8800 0.030067379
9000 0.02955919
9200 0.029067954
9400 0.028592853
9600 0.028133085
9800 0.027687898
10000 0.02725651


In [6]:
## testing (training set)

h, c, a = sess.run([model, prediction, accuracy], feed_dict={X:x_data, Y:y_data})
print("\nModel:\n", h, "\nCorrect:\n ", c, "\nAccuracy:\n ", a)


Model:
 [[1.0544243e-05]
 [1.0987185e-03]
 [1.0292823e-01]
 [9.2289203e-01]
 [9.9919969e-01]
 [9.9999237e-01]
 [9.9999988e-01]] 
Correct:
  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
  1.0


# Answer

In [7]:
a=sess.run(model, feed_dict={X:[[9,9,9,9,9],[0,0,0,0,0],[10,10,10,10,10]]})

for i in range(3): 
    if a[i]>0.5:
        print (i,"th data는 1로 classified")
    else:
        print (i, "th data는 0으로 classified")


0 th data는 1로 classified
1 th data는 0으로 classified
2 th data는 1로 classified


In [8]:
b=sess.run(prediction, feed_dict={X:[[9,9,9,9,9],[0,0,0,0,0],[10,10,10,10,10]]})

print(b)

[[1.]
 [0.]
 [1.]]
