In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# problem

In [2]:
'''
Q. check whether given datas are [0,0,1] or [0,1,0] or [1,0,0] respectively.
'''

'\nQ. check whether given datas are [0,0,1] or [0,1,0] or [1,0,0] respectively.\n'

In [3]:
x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

In [4]:
# x_data의 dimension=4
dimx=4
# y_data의 dimension=3
dimy=3

# solution

In [5]:
X= tf.placeholder(tf.float32, shape=[None, dimx])
Y= tf.placeholder(tf.float32, shape=[None, dimy])

W= tf.Variable(tf.random_normal([dimx, dimy]), name='weight')
b= tf.Variable(tf.random_normal([dimy]), name='bias')

model= tf.nn.softmax(tf.add(tf.matmul(X, W), b)) #linear regression
cost= tf.reduce_mean(tf.reduce_sum((-1)*Y*tf.log(model), axis=1))
train=tf.train.GradientDescentOptimizer(learning_rate=0.20).minimize(cost)

In [6]:
sess= tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val_, _=sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))

0 4.7362585
200 1.401448
400 1.1615798
600 0.9434612
800 0.74945974
1000 0.56057197
1200 0.088108726
1400 0.07985258
1600 0.07347649
1800 0.06822955
2000 0.06378271


# testing

In [7]:
testdata1=[1, 11, 7, 9]
testdata2=[1, 3, 4, 3]
testdata3=[1, 1, 0, 1]
testdata=[testdata1, testdata2, testdata3] 

In [8]:
result=sess.run(model, feed_dict={X: testdata})
print(result, sess.run(tf.argmax(result, 1))+1, "번째")

[[2.2965301e-05 9.9997628e-01 6.9530859e-07]
 [9.8101509e-01 1.7848538e-02 1.1363304e-03]
 [2.0241724e-13 1.3628941e-05 9.9998641e-01]] [2 1 3] 번째
